import type { VoiceVoice } from '../types'

export const MINIMAX_VOICES: VoiceVoice[] = [
  { id: 'male-qn-qingse', name: '青涩青年音色', description: '清澈、年轻的男声', gender: 'male', language: '中文' },
  { id: 'male-qn-jingying', name: '精英青年音色', description: '沉稳、专业的男声', gender: 'male', language: '中文' },
  { id: 'male-qn-badao', name: '霸道青年音色', description: '强势、有力的男声', gender: 'male', language: '中文' },
  { id: 'male-qn-daxuesheng', name: '青年大学生音色', description: '阳光、活力的男声', gender: 'male', language: '中文' },
  { id: 'female-shaonv', name: '少女音色', description: '甜美、活泼的女声', gender: 'female', language: '中文' },
  { id: 'female-yujie', name: '御姐音色', description: '成熟、优雅的女声', gender: 'female', language: '中文' },
  { id: 'female-chengshu', name: '成熟女性音色', description: '稳重、知性的女声', gender: 'female', language: '中文' },
  { id: 'female-tianmei', name: '甜美女性音色', description: '温柔、甜美的女声', gender: 'female', language: '中文' },
  { id: 'male-qn-qingse-jingpin', name: '青涩青年音色-beta', description: '清澈、年轻的男声Beta版', gender: 'male', language: '中文' },
  { id: 'male-qn-jingying-jingpin', name: '精英青年音色-beta', description: '沉稳、专业的男声Beta版', gender: 'male', language: '中文' },
  { id: 'male-qn-badao-jingpin', name: '霸道青年音色-beta', description: '强势、有力的男声Beta版', gender: 'male', language: '中文' },
  { id: 'male-qn-daxuesheng-jingpin', name: '青年大学生音色-beta', description: '阳光、活力的男声Beta版', gender: 'male', language: '中文' },
  { id: 'female-shaonv-jingpin', name: '少女音色-beta', description: '甜美、活泼的女声Beta版', gender: 'female', language: '中文' },
  { id: 'female-yujie-jingpin', name: '御姐音色-beta', description: '成熟、优雅的女声Beta版', gender: 'female', language: '中文' },
  { id: 'female-chengshu-jingpin', name: '成熟女性音色-beta', description: '稳重、知性的女声Beta版', gender: 'female', language: '中文' },
  { id: 'female-tianmei-jingpin', name: '甜美女性音色-beta', description: '温柔、甜美的女声Beta版', gender: 'female', language: '中文' },
  { id: 'clever_boy', name: '聪明男童', description: '聪明伶俐的男童声', gender: 'male', language: '中文' },
  { id: 'cute_boy', name: '可爱男童', description: '可爱活泼的男童声', gender: 'male', language: '中文' },
  { id: 'lovely_girl', name: '萌萌女童', description: '萌萌可爱的女童声', gender: 'female', language: '中文' },
  { id: 'cartoon_pig', name: '卡通猪小琪', description: '可爱的卡通猪角色', gender: 'neutral', language: '中文' },
  { id: 'bingjiao_didi', name: '病娇弟弟', description: '病娇风格的弟弟声', gender: 'male', language: '中文' },
  { id: 'junlang_nanyou', name: '俊朗男友', description: '俊朗帅气的男友声', gender: 'male', language: '中文' },
  { id: 'chunzhen_xuedi', name: '纯真学弟', description: '纯真可爱的学弟声', gender: 'male', language: '中文' },
  { id: 'lengdan_xiongzhang', name: '冷淡学长', description: '冷淡疏离的学长声', gender: 'male', language: '中文' },
  { id: 'badao_shaoye', name: '霸道少爷', description: '霸道强势的少爷声', gender: 'male', language: '中文' },
  { id: 'tianxin_xiaoling', name: '甜心小玲', description: '甜心可爱的小玲声', gender: 'female', language: '中文' },
  { id: 'qiaopi_mengmei', name: '俏皮萌妹', description: '俏皮可爱的萌妹声', gender: 'female', language: '中文' },
  { id: 'wumei_yujie', name: '妩媚御姐', description: '妩媚迷人的御姐声', gender: 'female', language: '中文' },
  { id: 'diadia_xuemei', name: '嗲嗲学妹', description: '嗲嗲可爱的学妹声', gender: 'female', language: '中文' },
  { id: 'danya_xuejie', name: '淡雅学姐', description: '淡雅优雅的学姐声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Reliable_Executive', name: '沉稳高管', description: '沉稳可靠的高管声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_News_Anchor', name: '新闻女声', description: '专业新闻女声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Mature_Woman', name: '傲娇御姐', description: '傲娇成熟的御姐声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Unrestrained_Young_Man', name: '不羁青年', description: '不羁洒脱的青年声', gender: 'male', language: '中文' },
  { id: 'Arrogant_Miss', name: '嚣张小姐', description: '嚣张傲慢的小姐声', gender: 'female', language: '中文' },
  { id: 'Robot_Armor', name: '机械战甲', description: '机械科幻的战甲声', gender: 'neutral', language: '中文' },
  { id: 'Chinese (Mandarin)_Kind-hearted_Antie', name: '热心大婶', description: '热心善良的大婶声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_HK_Flight_Attendant', name: '港普空姐', description: '港普口音的空姐声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Humorous_Elder', name: '搞笑大爷', description: '幽默风趣的大爷声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Gentleman', name: '温润男声', description: '温润如玉的男声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Warm_Bestie', name: '温暖闺蜜', description: '温暖贴心的闺蜜声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Male_Announcer', name: '播报男声', description: '专业播报男声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Sweet_Lady', name: '甜美女声', description: '甜美动人的女声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Southern_Young_Man', name: '南方小哥', description: '南方口音的小哥声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Wise_Women', name: '阅历姐姐', description: '阅历丰富的姐姐声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Gentle_Youth', name: '温润青年', description: '温润温和的青年声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Warm_Girl', name: '温暖少女', description: '温暖可人的少女声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Kind-hearted_Elder', name: '花甲奶奶', description: '慈祥善良的奶奶声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Cute_Spirit', name: '憨憨萌兽', description: '憨憨可爱的萌兽声', gender: 'neutral', language: '中文' },
  { id: 'Chinese (Mandarin)_Radio_Host', name: '电台男主播', description: '电台风格男主播', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Lyrical_Voice', name: '抒情男声', description: '抒情动人的男声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Straightforward_Boy', name: '率真弟弟', description: '率真直爽的弟弟声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Sincere_Adult', name: '真诚青年', description: '真诚可靠的青年声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Gentle_Senior', name: '温柔学姐', description: '温柔体贴的学姐声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Stubborn_Friend', name: '嘴硬竹马', description: '嘴硬傲娇的竹马声', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Crisp_Girl', name: '清脆少女', description: '清脆悦耳的少女声', gender: 'female', language: '中文' },
  { id: 'Chinese (Mandarin)_Pure-hearted_Boy', name: '清澈邻家弟弟', description: '清澈纯真的邻家弟弟', gender: 'male', language: '中文' },
  { id: 'Chinese (Mandarin)_Soft_Girl', name: '柔和少女', description: '柔和温婉的少女声', gender: 'female', language: '中文' },
  { id: 'Cantonese_ProfessionalHost（F)', name: '专业女主持', description: '粤语专业女主持声', gender: 'female', language: '粤语' },
  { id: 'Cantonese_GentleLady', name: '温柔女声', description: '粤语温柔女声', gender: 'female', language: '粤语' },
  { id: 'Cantonese_ProfessionalHost（M)', name: '专业男主持', description: '粤语专业男主持声', gender: 'male', language: '粤语' },
  { id: 'Cantonese_PlayfulMan', name: '活泼男声', description: '粤语活泼男声', gender: 'male', language: '粤语' },
  { id: 'Cantonese_CuteGirl', name: '可爱女孩', description: '粤语可爱女孩声', gender: 'female', language: '粤语' },
  { id: 'Cantonese_KindWoman', name: '善良女声', description: '粤语善良女声', gender: 'female', language: '粤语' },
  { id: 'Santa_Claus', name: 'Santa Claus', description: '圣诞老人声', gender: 'male', language: '英文' },
  { id: 'Grinch', name: 'Grinch', description: '格林奇声', gender: 'male', language: '英文' },
  { id: 'Rudolph', name: 'Rudolph', description: '鲁道夫声', gender: 'male', language: '英文' },
  { id: 'Arnold', name: 'Arnold', description: '阿诺德声', gender: 'male', language: '英文' },
  { id: 'Charming_Santa', name: 'Charming Santa', description: '迷人圣诞老人声', gender: 'male', language: '英文' },
  { id: 'Charming_Lady', name: 'Charming Lady', description: '迷人女士声', gender: 'female', language: '英文' },
  { id: 'Sweet_Girl', name: 'Sweet Girl', description: '甜美女孩声', gender: 'female', language: '英文' },
  { id: 'Cute_Elf', name: 'Cute Elf', description: '可爱精灵声', gender: 'neutral', language: '英文' },
  { id: 'Attractive_Girl', name: 'Attractive Girl', description: '迷人女孩声', gender: 'female', language: '英文' },
  { id: 'Serene_Woman', name: 'Serene Woman', description: '宁静女士声', gender: 'female', language: '英文' },
  { id: 'English_Trustworthy_Man', name: 'Trustworthy Man', description: '值得信赖的男士声', gender: 'male', language: '英文' },
  { id: 'English_Graceful_Lady', name: 'Graceful Lady', description: '优雅女士声', gender: 'female', language: '英文' },
  { id: 'English_Aussie_Bloke', name: 'Aussie Bloke', description: '澳洲男士声', gender: 'male', language: '英文' },
  { id: 'English_Whispering_girl', name: 'Whispering girl', description: '耳语女孩声', gender: 'female', language: '英文' },
  { id: 'English_Diligent_Man', name: 'Diligent Man', description: '勤奋男士声', gender: 'male', language: '英文' },
  { id: 'English_Gentle-voiced_man', name: 'Gentle-voiced man', description: '温和男士声', gender: 'male', language: '英文' },
  { id: 'Japanese_IntellectualSenior', name: 'Intellectual Senior', description: '知性前辈声', gender: 'male', language: '日文' },
  { id: 'Japanese_DecisivePrincess', name: 'Decisive Princess', description: '果断公主声', gender: 'female', language: '日文' },
  { id: 'Japanese_LoyalKnight', name: 'Loyal Knight', description: '忠诚骑士声', gender: 'male', language: '日文' },
  { id: 'Japanese_DominantMan', name: 'Dominant Man', description: '强势男士声', gender: 'male', language: '日文' },
  { id: 'Japanese_SeriousCommander', name: 'Serious Commander', description: '严肃指挥官声', gender: 'male', language: '日文' },
  { id: 'Japanese_ColdQueen', name: 'Cold Queen', description: '冷酷女王声', gender: 'female', language: '日文' },
  { id: 'Japanese_DependableWoman', name: 'Dependable Woman', description: '可靠女士声', gender: 'female', language: '日文' },
  { id: 'Japanese_GentleButler', name: 'Gentle Butler', description: '温柔管家声', gender: 'male', language: '日文' },
  { id: 'Japanese_KindLady', name: 'Kind Lady', description: '善良女士声', gender: 'female', language: '日文' },
  { id: 'Japanese_CalmLady', name: 'Calm Lady', description: '冷静女士声', gender: 'female', language: '日文' },
  { id: 'Japanese_OptimisticYouth', name: 'Optimistic Youth', description: '乐观青年声', gender: 'male', language: '日文' },
  { id: 'Japanese_GenerousIzakayaOwner', name: 'Generous Izakaya Owner', description: '慷慨居酒屋老板声', gender: 'male', language: '日文' },
  { id: 'Japanese_SportyStudent', name: 'Sporty Student', description: '运动学生声', gender: 'male', language: '日文' },
  { id: 'Japanese_InnocentBoy', name: 'Innocent Boy', description: '天真男孩声', gender: 'male', language: '日文' },
  { id: 'Japanese_GracefulMaiden', name: 'Graceful Maiden', description: '优雅少女声', gender: 'female', language: '日文' },
  { id: 'Korean_SweetGirl', name: 'Sweet Girl', description: '甜美女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_CheerfulBoyfriend', name: 'Cheerful Boyfriend', description: '开朗男友声', gender: 'male', language: '韩文' },
  { id: 'Korean_EnchantingSister', name: 'Enchanting Sister', description: '迷人姐姐声', gender: 'female', language: '韩文' },
  { id: 'Korean_ShyGirl', name: 'Shy Girl', description: '害羞女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_ReliableSister', name: 'Reliable Sister', description: '可靠姐姐声', gender: 'female', language: '韩文' },
  { id: 'Korean_StrictBoss', name: 'Strict Boss', description: '严厉老板声', gender: 'male', language: '韩文' },
  { id: 'Korean_SassyGirl', name: 'Sassy Girl', description: '时髦女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_ChildhoodFriendGirl', name: 'Childhood Friend Girl', description: '青梅竹马女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_PlayboyCharmer', name: 'Playboy Charmer', description: '花花公子声', gender: 'male', language: '韩文' },
  { id: 'Korean_ElegantPrincess', name: 'Elegant Princess', description: '优雅公主声', gender: 'female', language: '韩文' },
  { id: 'Korean_BraveFemaleWarrior', name: 'Brave Female Warrior', description: '勇敢女战士声', gender: 'female', language: '韩文' },
  { id: 'Korean_BraveYouth', name: 'Brave Youth', description: '勇敢青年声', gender: 'male', language: '韩文' },
  { id: 'Korean_CalmLady', name: 'Calm Lady', description: '冷静女士声', gender: 'female', language: '韩文' },
  { id: 'Korean_EnthusiasticTeen', name: 'Enthusiastic Teen', description: '热情少年声', gender: 'male', language: '韩文' },
  { id: 'Korean_SoothingLady', name: 'Soothing Lady', description: '抚慰女士声', gender: 'female', language: '韩文' },
  { id: 'Korean_IntellectualSenior', name: 'Intellectual Senior', description: '知性前辈声', gender: 'male', language: '韩文' },
  { id: 'Korean_LonelyWarrior', name: 'Lonely Warrior', description: '孤独战士声', gender: 'male', language: '韩文' },
  { id: 'Korean_MatureLady', name: 'Mature Lady', description: '成熟女士声', gender: 'female', language: '韩文' },
  { id: 'Korean_InnocentBoy', name: 'Innocent Boy', description: '天真男孩声', gender: 'male', language: '韩文' },
  { id: 'Korean_CharmingSister', name: 'Charming Sister', description: '迷人姐姐声', gender: 'female', language: '韩文' },
  { id: 'Korean_AthleticStudent', name: 'Athletic Student', description: '运动学生声', gender: 'male', language: '韩文' },
  { id: 'Korean_BraveAdventurer', name: 'Brave Adventurer', description: '勇敢冒险家声', gender: 'male', language: '韩文' },
  { id: 'Korean_CalmGentleman', name: 'Calm Gentleman', description: '冷静绅士声', gender: 'male', language: '韩文' },
  { id: 'Korean_WiseElf', name: 'Wise Elf', description: '智慧精灵声', gender: 'neutral', language: '韩文' },
  { id: 'Korean_CheerfulCoolJunior', name: 'Cheerful Cool Junior', description: '开朗酷学弟声', gender: 'male', language: '韩文' },
  { id: 'Korean_DecisiveQueen', name: 'Decisive Queen', description: '果断女王声', gender: 'female', language: '韩文' },
  { id: 'Korean_ColdYoungMan', name: 'Cold Young Man', description: '冷酷青年声', gender: 'male', language: '韩文' },
  { id: 'Korean_MysteriousGirl', name: 'Mysterious Girl', description: '神秘女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_QuirkyGirl', name: 'Quirky Girl', description: '古怪女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_ConsiderateSenior', name: 'Considerate Senior', description: '体贴前辈声', gender: 'male', language: '韩文' },
  { id: 'Korean_CheerfulLittleSister', name: 'Cheerful Little Sister', description: '开朗妹妹声', gender: 'female', language: '韩文' },
  { id: 'Korean_DominantMan', name: 'Dominant Man', description: '强势男士声', gender: 'male', language: '韩文' },
  { id: 'Korean_AirheadedGirl', name: 'Airheaded Girl', description: '天然呆女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_ReliableYouth', name: 'Reliable Youth', description: '可靠青年声', gender: 'male', language: '韩文' },
  { id: 'Korean_FriendlyBigSister', name: 'Friendly Big Sister', description: '友好姐姐声', gender: 'female', language: '韩文' },
  { id: 'Korean_GentleBoss', name: 'Gentle Boss', description: '温柔老板声', gender: 'male', language: '韩文' },
  { id: 'Korean_ColdGirl', name: 'Cold Girl', description: '冷酷女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_HaughtyLady', name: 'Haughty Lady', description: '傲慢女士声', gender: 'female', language: '韩文' },
  { id: 'Korean_CharmingElderSister', name: 'Charming Elder Sister', description: '迷人姐姐声', gender: 'female', language: '韩文' },
  { id: 'Korean_IntellectualMan', name: 'Intellectual Man', description: '知性男士声', gender: 'male', language: '韩文' },
  { id: 'Korean_CaringWoman', name: 'Caring Woman', description: '体贴女士声', gender: 'female', language: '韩文' },
  { id: 'Korean_WiseTeacher', name: 'Wise Teacher', description: '智慧老师声', gender: 'male', language: '韩文' },
  { id: 'Korean_ConfidentBoss', name: 'Confident Boss', description: '自信老板声', gender: 'male', language: '韩文' },
  { id: 'Korean_AthleticGirl', name: 'Athletic Girl', description: '运动女孩声', gender: 'female', language: '韩文' },
  { id: 'Korean_PossessiveMan', name: 'Possessive Man', description: '占有欲男士声', gender: 'male', language: '韩文' },
  { id: 'Korean_GentleWoman', name: 'Gentle Woman', description: '温柔女士声', gender: 'female', language: '韩文' },
  { id: 'Korean_CockyGuy', name: 'Cocky Guy', description: '自大男士声', gender: 'male', language: '韩文' },
  { id: 'Korean_ThoughtfulWoman', name: 'Thoughtful Woman', description: '体贴女士声', gender: 'female', language: '韩文' },
  { id: 'Korean_OptimisticYouth', name: 'Optimistic Youth', description: '乐观青年声', gender: 'male', language: '韩文' },
  { id: 'Spanish_SereneWoman', name: 'Serene Woman', description: '宁静女士声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_MaturePartner', name: 'Mature Partner', description: '成熟伴侣声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_CaptivatingStoryteller', name: 'Captivating Storyteller', description: '迷人讲述者声', gender: 'neutral', language: '西班牙文' },
  { id: 'Spanish_Narrator', name: 'Narrator', description: '叙述者声', gender: 'neutral', language: '西班牙文' },
  { id: 'Spanish_WiseScholar', name: 'Wise Scholar', description: '智慧学者声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Kind-heartedGirl', name: 'Kind-hearted Girl', description: '善良女孩声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_DeterminedManager', name: 'Determined Manager', description: '果断经理声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_BossyLeader', name: 'Bossy Leader', description: '专横领导声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_ReservedYoungMan', name: 'Reserved Young Man', description: '内向青年声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_ConfidentWoman', name: 'Confident Woman', description: '自信女士声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_ThoughtfulMan', name: 'Thoughtful Man', description: '体贴男士声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Strong-WilledBoy', name: 'Strong-willed Boy', description: '坚强男孩声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_SophisticatedLady', name: 'Sophisticated Lady', description: '精致女士声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_RationalMan', name: 'Rational Man', description: '理性男士声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Deep-tonedMan', name: 'Deep-toned Man', description: '低沉男士声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Fussyhostess', name: 'Fussy hostess', description: '挑剔女主人声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_SincereTeen', name: 'Sincere Teen', description: '真诚少年声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_FrankLady', name: 'Frank Lady', description: '坦率女士声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_Comedian', name: 'Comedian', description: '喜剧演员声', gender: 'neutral', language: '西班牙文' },
  { id: 'Spanish_Debator', name: 'Debator', description: '辩论者声', gender: 'neutral', language: '西班牙文' },
  { id: 'Spanish_ToughBoss', name: 'Tough Boss', description: '强硬老板声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Wiselady', name: 'Wise Lady', description: '智慧女士声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_Steadymentor', name: 'Steady Mentor', description: '稳重导师声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Jovialman', name: 'Jovial Man', description: '快乐男士声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_SantaClaus', name: 'Santa Claus', description: '圣诞老人声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Rudolph', name: 'Rudolph', description: '鲁道夫声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Intonategirl', name: 'Intonate Girl', description: '抑扬顿挫女孩声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_Arnold', name: 'Arnold', description: '阿诺德声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_Ghost', name: 'Ghost', description: '幽灵声', gender: 'neutral', language: '西班牙文' },
  { id: 'Spanish_HumorousElder', name: 'Humorous Elder', description: '幽默长者声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_EnergeticBoy', name: 'Energetic Boy', description: '活力男孩声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_WhimsicalGirl', name: 'Whimsical Girl', description: '异想天开女孩声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_StrictBoss', name: 'Strict Boss', description: '严厉老板声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_ReliableMan', name: 'Reliable Man', description: '可靠男士声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_SereneElder', name: 'Serene Elder', description: '宁静长者声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_AngryMan', name: 'Angry Man', description: '愤怒男士声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_AssertiveQueen', name: 'Assertive Queen', description: '自信女王声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_CaringGirlfriend', name: 'Caring Girlfriend', description: '体贴女友声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_PowerfulSoldier', name: 'Powerful Soldier', description: '强大士兵声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_PassionateWarrior', name: 'Passionate Warrior', description: '热情战士声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_ChattyGirl', name: 'Chatty Girl', description: '健谈女孩声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_RomanticHusband', name: 'Romantic Husband', description: '浪漫丈夫声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_CompellingGirl', name: 'Compelling Girl', description: '迷人女孩声', gender: 'female', language: '西班牙文' },
  { id: 'Spanish_PowerfulVeteran', name: 'Powerful Veteran', description: '强大老兵声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_SensibleManager', name: 'Sensible Manager', description: '明智经理声', gender: 'male', language: '西班牙文' },
  { id: 'Spanish_ThoughtfulLady', name: 'Thoughtful Lady', description: '体贴女士声', gender: 'female', language: '西班牙文' },
  { id: 'Portuguese_SentimentalLady', name: 'Sentimental Lady', description: '感性女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_BossyLeader', name: 'Bossy Leader', description: '专横领导声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Wiselady', name: 'Wise lady', description: '智慧女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Strong-WilledBoy', name: 'Strong-willed Boy', description: '坚强男孩声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Deep-VoicedGentleman', name: 'Deep-voiced Gentleman', description: '低沉绅士声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_UpsetGirl', name: 'Upset Girl', description: '不安女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_PassionateWarrior', name: 'Passionate Warrior', description: '热情战士声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_ConfidentWoman', name: 'Confident Woman', description: '自信女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_AngryMan', name: 'Angry Man', description: '愤怒男士声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_CaptivatingStoryteller', name: 'Captivating Storyteller', description: '迷人讲述者声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_Godfather', name: 'Godfather', description: '教父声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_ReservedYoungMan', name: 'Reserved Young Man', description: '内向青年声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_SmartYoungGirl', name: 'Smart Young Girl', description: '聪明女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Kind-heartedGirl', name: 'Kind-hearted Girl', description: '善良女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Pompouslady', name: 'Pompous lady', description: '浮夸女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Grinch', name: 'Grinch', description: '格林奇声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Debator', name: 'Debator', description: '辩论者声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_SweetGirl', name: 'Sweet Girl', description: '甜美女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_AttractiveGirl', name: 'Attractive Girl', description: '迷人女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_ThoughtfulMan', name: 'Thoughtful Man', description: '体贴男士声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_PlayfulGirl', name: 'Playful Girl', description: '顽皮女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_GorgeousLady', name: 'Gorgeous Lady', description: '华丽女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_LovelyLady', name: 'Lovely Lady', description: '可爱女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_SereneWoman', name: 'Serene Woman', description: '宁静女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_SadTeen', name: 'Sad Teen', description: '悲伤少年声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_MaturePartner', name: 'Mature Partner', description: '成熟伴侣声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Comedian', name: 'Comedian', description: '喜剧演员声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_NaughtySchoolgirl', name: 'Naughty Schoolgirl', description: '顽皮女学生声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Narrator', name: 'Narrator', description: '叙述者声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_ToughBoss', name: 'Tough Boss', description: '强硬老板声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Fussyhostess', name: 'Fussy hostess', description: '挑剔女主人声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Dramatist', name: 'Dramatist', description: '戏剧家声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_Steadymentor', name: 'Steady Mentor', description: '稳重导师声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Jovialman', name: 'Jovial Man', description: '快乐男士声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_CharmingQueen', name: 'Charming Queen', description: '迷人女王声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_SantaClaus', name: 'Santa Claus', description: '圣诞老人声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Rudolph', name: 'Rudolph', description: '鲁道夫声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_Arnold', name: 'Arnold', description: '阿诺德声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_CharmingSanta', name: 'Charming Santa', description: '迷人圣诞老人声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_CharmingLady', name: 'Charming Lady', description: '迷人女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Ghost', name: 'Ghost', description: '幽灵声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_HumorousElder', name: 'Humorous Elder', description: '幽默长者声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_CalmLeader', name: 'Calm Leader', description: '冷静领导声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_GentleTeacher', name: 'Gentle Teacher', description: '温柔老师声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_EnergeticBoy', name: 'Energetic Boy', description: '活力男孩声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_ReliableMan', name: 'Reliable Man', description: '可靠男士声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_SereneElder', name: 'Serene Elder', description: '宁静长者声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_GrimReaper', name: 'Grim Reaper', description: '死神声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_AssertiveQueen', name: 'Assertive Queen', description: '自信女王声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_WhimsicalGirl', name: 'Whimsical Girl', description: '异想天开女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_StressedLady', name: 'Stressed Lady', description: '压力女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_FriendlyNeighbor', name: 'Friendly Neighbor', description: '友好邻居声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_CaringGirlfriend', name: 'Caring Girlfriend', description: '体贴女友声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_PowerfulSoldier', name: 'Powerful Soldier', description: '强大士兵声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_FascinatingBoy', name: 'Fascinating Boy', description: '迷人男孩声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_RomanticHusband', name: 'Romantic Husband', description: '浪漫丈夫声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_StrictBoss', name: 'Strict Boss', description: '严厉老板声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_InspiringLady', name: 'Inspiring Lady', description: '鼓舞女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_PlayfulSpirit', name: 'Playful Spirit', description: '顽皮精灵声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_ElegantGirl', name: 'Elegant Girl', description: '优雅女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_CompellingGirl', name: 'Compelling Girl', description: '迷人女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_PowerfulVeteran', name: 'Powerful Veteran', description: '强大老兵声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_SensibleManager', name: 'Sensible Manager', description: '明智经理声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_ThoughtfulLady', name: 'Thoughtful Lady', description: '体贴女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_TheatricalActor', name: 'Theatrical Actor', description: '戏剧演员声', gender: 'neutral', language: '葡萄牙文' },
  { id: 'Portuguese_FragileBoy', name: 'Fragile Boy', description: '脆弱男孩声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_ChattyGirl', name: 'Chatty Girl', description: '健谈女孩声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_Conscientiousinstructor', name: 'Conscientious Instructor', description: '认真指导员声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_RationalMan', name: 'Rational Man', description: '理性男士声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_WiseScholar', name: 'Wise Scholar', description: '智慧学者声', gender: 'male', language: '葡萄牙文' },
  { id: 'Portuguese_FrankLady', name: 'Frank Lady', description: '坦率女士声', gender: 'female', language: '葡萄牙文' },
  { id: 'Portuguese_DeterminedManager', name: 'Determined Manager', description: '果断经理声', gender: 'male', language: '葡萄牙文' },
  { id: 'French_Male_Speech_New', name: 'Level-Headed Man', description: '冷静男士声', gender: 'male', language: '法文' },
  { id: 'French_Female_News Anchor', name: 'Patient Female Presenter', description: '耐心女主持声', gender: 'female', language: '法文' },
  { id: 'French_CasualMan', name: 'Casual Man', description: '随意男士声', gender: 'male', language: '法文' },
  { id: 'French_MovieLeadFemale', name: 'Movie Lead Female', description: '电影女主角声', gender: 'female', language: '法文' },
  { id: 'French_FemaleAnchor', name: 'Female Anchor', description: '女主持声', gender: 'female', language: '法文' },
  { id: 'French_MaleNarrator', name: 'Male Narrator', description: '男叙述者声', gender: 'male', language: '法文' },
  { id: 'Indonesian_SweetGirl', name: 'Sweet Girl', description: '甜美女孩声', gender: 'female', language: '印尼文' },
  { id: 'Indonesian_ReservedYoungMan', name: 'Reserved Young Man', description: '内向青年声', gender: 'male', language: '印尼文' },
  { id: 'Indonesian_CharmingGirl', name: 'Charming Girl', description: '迷人女孩声', gender: 'female', language: '印尼文' },
  { id: 'Indonesian_CalmWoman', name: 'Calm Woman', description: '冷静女士声', gender: 'female', language: '印尼文' },
  { id: 'Indonesian_ConfidentWoman', name: 'Confident Woman', description: '自信女士声', gender: 'female', language: '印尼文' },
  { id: 'Indonesian_CaringMan', name: 'Caring Man', description: '体贴男士声', gender: 'male', language: '印尼文' },
  { id: 'Indonesian_BossyLeader', name: 'Bossy Leader', description: '专横领导声', gender: 'male', language: '印尼文' },
  { id: 'Indonesian_DeterminedBoy', name: 'Determined Boy', description: '果断男孩声', gender: 'male', language: '印尼文' },
  { id: 'Indonesian_GentleGirl', name: 'Gentle Girl', description: '温柔女孩声', gender: 'female', language: '印尼文' },
  { id: 'German_FriendlyMan', name: 'Friendly Man', description: '友好男士声', gender: 'male', language: '德文' },
  { id: 'German_SweetLady', name: 'Sweet Lady', description: '甜美女士声', gender: 'female', language: '德文' },
  { id: 'German_PlayfulMan', name: 'Playful Man', description: '顽皮男士声', gender: 'male', language: '德文' },
  { id: 'Russian_HandsomeChildhoodFriend', name: 'Handsome Childhood Friend', description: '帅气青梅竹马声', gender: 'male', language: '俄文' },
  { id: 'Russian_BrightHeroine', name: 'Bright Queen', description: '明亮女王声', gender: 'female', language: '俄文' },
  { id: 'Russian_AmbitiousWoman', name: 'Ambitious Woman', description: '有抱负女士声', gender: 'female', language: '俄文' },
  { id: 'Russian_ReliableMan', name: 'Reliable Man', description: '可靠男士声', gender: 'male', language: '俄文' },
  { id: 'Russian_CrazyQueen', name: 'Crazy Girl', description: '疯狂女孩声', gender: 'female', language: '俄文' },
  { id: 'Russian_PessimisticGirl', name: 'Pessimistic Girl', description: '悲观女孩声', gender: 'female', language: '俄文' },
  { id: 'Russian_AttractiveGuy', name: 'Attractive Guy', description: '迷人男士声', gender: 'male', language: '俄文' },
  { id: 'Russian_Bad-temperedBoy', name: 'Bad-tempered Boy', description: '脾气暴躁男孩声', gender: 'male', language: '俄文' },
  { id: 'Italian_BraveHeroine', name: 'Brave Heroine', description: '勇敢女主角声', gender: 'female', language: '意大利文' },
  { id: 'Italian_Narrator', name: 'Narrator', description: '叙述者声', gender: 'neutral', language: '意大利文' },
  { id: 'Italian_WanderingSorcerer', name: 'Wandering Sorcerer', description: '流浪巫师声', gender: 'male', language: '意大利文' },
  { id: 'Italian_DiligentLeader', name: 'Diligent Leader', description: '勤奋领导声', gender: 'male', language: '意大利文' },
  { id: 'Arabic_CalmWoman', name: 'Calm Woman', description: '冷静女士声', gender: 'female', language: '阿拉伯文' },
  { id: 'Arabic_FriendlyGuy', name: 'Friendly Guy', description: '友好男士声', gender: 'male', language: '阿拉伯文' },
  { id: 'Turkish_CalmWoman', name: 'Calm Woman', description: '冷静女士声', gender: 'female', language: '土耳其文' },
  { id: 'Turkish_Trustworthyman', name: 'Trustworthy man', description: '值得信赖男士声', gender: 'male', language: '土耳其文' },
  { id: 'Ukrainian_CalmWoman', name: 'Calm Woman', description: '冷静女士声', gender: 'female', language: '乌克兰文' },
  { id: 'Ukrainian_WiseScholar', name: 'Wise Scholar', description: '智慧学者声', gender: 'male', language: '乌克兰文' },
  { id: 'Dutch_kindhearted_girl', name: 'Kind-hearted girl', description: '善良女孩声', gender: 'female', language: '荷兰文' },
  { id: 'Dutch_bossy_leader', name: 'Bossy leader', description: '专横领导声', gender: 'male', language: '荷兰文' },
  { id: 'Vietnamese_kindhearted_girl', name: 'Kind-hearted girl', description: '善良女孩声', gender: 'female', language: '越南文' },
  { id: 'Thai_male_1_sample8', name: 'Serene Man', description: '宁静男士声', gender: 'male', language: '泰文' },
  { id: 'Thai_male_2_sample2', name: 'Friendly Man', description: '友好男士声', gender: 'male', language: '泰文' },
  { id: 'Thai_female_1_sample1', name: 'Confident Woman', description: '自信女士声', gender: 'female', language: '泰文' },
  { id: 'Thai_female_2_sample2', name: 'Energetic Woman', description: '活力女士声', gender: 'female', language: '泰文' },
  { id: 'Polish_male_1_sample4', name: 'Male Narrator', description: '男叙述者声', gender: 'male', language: '波兰文' },
  { id: 'Polish_male_2_sample3', name: 'Male Anchor', description: '男主持声', gender: 'male', language: '波兰文' },
  { id: 'Polish_female_1_sample1', name: 'Calm Woman', description: '冷静女士声', gender: 'female', language: '波兰文' },
  { id: 'Polish_female_2_sample3', name: 'Casual Woman', description: '随意女士声', gender: 'female', language: '波兰文' },
  { id: 'Romanian_male_1_sample2', name: 'Reliable Man', description: '可靠男士声', gender: 'male', language: '罗马尼亚文' },
  { id: 'Romanian_male_2_sample1', name: 'Energetic Youth', description: '活力青年声', gender: 'male', language: '罗马尼亚文' },
  { id: 'Romanian_female_1_sample4', name: 'Optimistic Youth', description: '乐观青年声', gender: 'male', language: '罗马尼亚文' },
  { id: 'Romanian_female_2_sample1', name: 'Gentle Woman', description: '温柔女士声', gender: 'female', language: '罗马尼亚文' },
  { id: 'greek_male_1a_v1', name: 'Thoughtful Mentor', description: '体贴导师声', gender: 'male', language: '希腊文' },
  { id: 'Greek_female_1_sample1', name: 'Gentle Lady', description: '温柔女士声', gender: 'female', language: '希腊文' },
  { id: 'Greek_female_2_sample3', name: 'Girl Next Door', description: '邻家女孩声', gender: 'female', language: '希腊文' },
  { id: 'czech_male_1_v1', name: 'Assured Presenter', description: '自信主持声', gender: 'male', language: '捷克文' },
  { id: 'czech_female_5_v7', name: 'Steadfast Narrator', description: '坚定叙述者声', gender: 'neutral', language: '捷克文' },
  { id: 'czech_female_2_v2', name: 'Elegant Lady', description: '优雅女士声', gender: 'female', language: '捷克文' },
  { id: 'finnish_male_3_v1', name: 'Upbeat Man', description: '乐观男士声', gender: 'male', language: '芬兰文' },
  { id: 'finnish_male_1_v2', name: 'Friendly Boy', description: '友好男孩声', gender: 'male', language: '芬兰文' },
  { id: 'finnish_female_4_v1', name: 'Assetive Woman', description: '自信女士声', gender: 'female', language: '芬兰文' },
  { id: 'hindi_male_1_v2', name: 'Trustworthy Advisor', description: '值得信赖顾问声', gender: 'male', language: '印地文' },
  { id: 'hindi_female_2_v1', name: 'Tranquil Woman', description: '宁静女士声', gender: 'female', language: '印地文' },
  { id: 'hindi_female_1_v2', name: 'News Anchor', description: '新闻主持声', gender: 'neutral', language: '印地文' },
]
